INSERT INTO product (description, price, create_at) VALUES('Macbook Air 13 pulgadas', 4899, NOW());
INSERT INTO product (description, price, create_at) VALUES('Laptop Lenovo 15.6" Ryzen 7', 3199, NOW());
INSERT INTO product (description, price, create_at) VALUES('Laptop Gamer IdeaPad3 Core i5', 3499, NOW());
INSERT INTO product (description, price, create_at) VALUES('Televisor 43" 4K Ultra HD', 899, NOW());
INSERT INTO product (description, price, create_at) VALUES('Televisor 50" 4K Ultra HD Smart TV', 1699, NOW());
INSERT INTO product (description, price, create_at) VALUES('Aire Acondicionado Portatil 15000 Btu', 999, NOW());
INSERT INTO product (description, price, create_at) VALUES('Consola Nintendo Switch 1.1 Neon', 1499, NOW());
INSERT INTO product (description, price, create_at) VALUES('Minicomponente AKX710PUK Negro 2000 W', 799, NOW());
INSERT INTO product (description, price, create_at) VALUES('Refrigerador Side ', 2799, NOW());
INSERT INTO product (description, price, create_at) VALUES('Lavadora Black Edition 22 kg', 2299, NOW());